/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.scalar.conf
 */
#ifndef RASPBERRYPISENSORS_H
#define RASPBERRYPISENSORS_H

/* function declarations */
void init_raspberryPiSensors(void);
Netsnmp_Node_Handler handle_sensorCurrent;
Netsnmp_Node_Handler handle_sensorVoltage;
Netsnmp_Node_Handler handle_sensorPower;
Netsnmp_Node_Handler handle_sensorDescription;
Netsnmp_Node_Handler handle_sensorAddress;
Netsnmp_Node_Handler handle_sensorLastUpdate;
Netsnmp_Node_Handler handle_sensorOperationalStatus;
Netsnmp_Node_Handler handle_sensorErrorCount;
Netsnmp_Node_Handler handle_sensorUptime;
Netsnmp_Node_Handler handle_gpuPowerLimit;

#endif /* RASPBERRYPISENSORS_H */
